services:
  lee:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - RUN_CRON=${RUN_CRON}
      - SSL_KEY=${SSL_KEY}
      - SSL_CERT=${SSL_CERT}
      - SSL_CA=${SSL_CA}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M
    restart: always
    command: >
      sh -c "     
        npm run start:prod
      "
